#ARG FROM_IMAGE_BASE=opensuse/leap:15.2
ARG FROM_IMAGE_BASE
FROM ${FROM_IMAGE_BASE}

WORKDIR /scratch
ARG REQUIREMENTS
COPY ${REQUIREMENTS} Requirements.txt

RUN zypper refresh \
    && zypper --non-interactive --quiet update \
        --auto-agree-with-licenses --no-recommends \
    && zypper --non-interactive --quiet install \
        --auto-agree-with-licenses --no-recommends `cat Requirements.txt` \
    && zypper clean \
    && rm -rf /var/cache/zypp/*
