# oraclelinux-8 is based on centos-8 (but without extra Powertools repo)
#
# docker run oraclelinux:8 dnf --version
#   4.2.23
#     Installed: dnf-0:4.2.23-4.el8.noarch at Thu Mar  4 17:44:31 2021
#     Built    :  at Thu Nov  5 16:58:32 2020
#
#     Installed: rpm-0:4.14.3-4.el8.x86_64 at Thu Mar  4 17:44:29 2021
#     Built    :  at Sun Aug  9 03:55:00 2020
#
# docker run --net=host oraclelinux:8 /bin/sh -c "dnf --assumeyes install dnf-plugins-core; dnf config-manager --set-enabled powertools; dnf repolist"
#   ...
#   Error: No matching repo to modify: powertools.
#   repo id                     repo name
#   ol8_appstream               Oracle Linux 8 Application Stream (x86_64)
#   ol8_baseos_latest           Oracle Linux 8 BaseOS Latest (x86_64)

ARG FROM_IMAGE_BASE
FROM ${FROM_IMAGE_BASE}

WORKDIR /scratch
ARG REQUIREMENTS
COPY ${REQUIREMENTS} Requirements.txt

# Oracle Linux 8 CodeReady Builder (x86_64) - Unsupported
RUN dnf --assumeyes install oraclelinux-release-el8 \
    && dnf config-manager --set-enabled ol8_codeready_builder

# Oracle Linux 8 Development Packages (x86_64)
#RUN dnf --assumeyes install oraclelinux-developer-release-el8

# Oracle Linux 8 EPEL Packages for Development (x86_64)
#RUN dnf --assumeyes install oracle-epel-release-el8

RUN dnf --assumeyes update \
    && dnf --assumeyes install `cat Requirements.txt` \
    && dnf clean all \
    && rm -rf /var/cache/dnf/* /var/lib/dnf/* /var/lib/rpm/*

RUN pip3 install junit2html
