ARG FROM_IMAGE_BASE
FROM ${FROM_IMAGE_BASE}

WORKDIR /scratch
ARG REQUIREMENTS
COPY ${REQUIREMENTS} Requirements.txt

ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=Etc/UTC
RUN apt-get update \
        --quiet=2 --assume-yes --no-install-recommends \
    && apt-get install \
        --quiet=2 --assume-yes --no-install-recommends `cat Requirements.txt` \
    && apt-get clean \
    && rm -rf /var/cache/apt/* /var/lib/apt/lists/*
