# SPDX-License-Identifier: MIT
ARG FROM_IMAGE_BASE
FROM ${FROM_IMAGE_BASE}

WORKDIR /scratch
ARG REQUIREMENTS
COPY ${REQUIREMENTS} Requirements.txt

RUN tdnf --assumeyes update \
    && tdnf --assumeyes install `cat Requirements.txt` \
    && tdnf clean all
