# SPDX-License-Identifier: MIT
# docker run centos:8 dnf --version
#   4.2.23
#     Installed: dnf-0:4.2.23-4.el8.noarch at Fri Dec  4 17:37:29 2020
#     Built    : CentOS Buildsys <bugs@centos.org> at Tue Aug  4 18:52:03 2020
#
#     Installed: rpm-0:4.14.3-4.el8.x86_64 at Fri Dec  4 17:37:26 2020
#     Built    : CentOS Buildsys <bugs@centos.org> at Tue Jul 21 17:36:08 2020
#
# docker run --net=host centos:8 /bin/sh -c "dnf --assumeyes install dnf-plugins-core; dnf config-manager --set-enabled powertools; dnf repolist"
#   ...
#   repo id                         repo name
#   appstream                       CentOS Linux 8 - AppStream
#   baseos                          CentOS Linux 8 - BaseOS
#   extras                          CentOS Linux 8 - Extras
#   powertools                      CentOS Linux 8 - PowerTools

ARG FROM_IMAGE_BASE
FROM ${FROM_IMAGE_BASE}

WORKDIR /scratch
ARG REQUIREMENTS
COPY ${REQUIREMENTS} Requirements.txt

# Enable `powertools` repo for development packages
RUN dnf --assumeyes install dnf-plugins-core \
    && dnf config-manager --set-enabled powertools

RUN dnf --assumeyes update \
    && dnf --assumeyes install `cat Requirements.txt` \
    && dnf clean all \
    && rm -rf /var/cache/dnf/*

RUN pip3 install junit2html
