#ARG FROM_IMAGE_BASE=alpine:3.13.4
ARG FROM_IMAGE_BASE
FROM ${FROM_IMAGE_BASE}

WORKDIR /scratch
ARG REQUIREMENTS
COPY ${REQUIREMENTS} Requirements.txt

RUN apk --update --no-cache add `cat Requirements.txt` && rm -rf /var/cache/apk
