ARG FROM_IMAGE_ARTIFACT
ARG FROM_IMAGE_BASE
FROM ${FROM_IMAGE_ARTIFACT} as TmpForCopy

ARG FROM_IMAGE_BASE
FROM ${FROM_IMAGE_BASE}

ARG ZEEK_PREFIX=/opt/zeek
COPY --from=TmpForCopy ${ZEEK_PREFIX} ${ZEEK_PREFIX}
ENV PATH="${ZEEK_PREFIX}/bin:$PATH"
